# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dreamus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dreamus
  pod 'RxSwift', '6.6.0'
  pod 'RxCocoa', '6.6.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Moya', '~> 15.0'
  pod 'ReactorKit'

  post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end

end
